export const CARD_SIZES = { width: 150, height: 233 };
export const DECK_SIZE = 15;


export const GAME_STATUS = 
{
  IN_PROGRESS: "IN_PROGRESS",
  LOADING: "LOADING",
  CREATING: "CREATING",
  CHECKING: "CHECKING",
  RESETTING: "RESETTING",
  FINISHED: "FINISHED"
};

export const CARD_STATUS = 
{
  SELECTED: "SELECTED",
  MATCHED: "MATCHED",
  HIDDEN: "HIDDEN"
};